# Generated by Django 4.2.1 on 2023-06-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="order_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="username",
        ),
        migrations.AddField(
            model_name="complaints",
            name="replay",
            field=models.CharField(default="No replay", max_length=500),
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(default=1, max_length=20, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="disabled.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaints",
            name="complaints",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name="shopreg",
            name="address",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="order_price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.CharField(max_length=20)),
                ("price_status", models.CharField(max_length=20)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30)),
                ("image", models.ImageField(max_length=20, upload_to="")),
                ("price", models.CharField(max_length=20)),
                ("quantity", models.CharField(max_length=20)),
                ("total_price", models.CharField(max_length=20)),
                ("cart_status", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disabled.userreg",
                    ),
                ),
            ],
        ),
    ]
