# Generated by Django 4.2.1 on 2023-06-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0002_rename_name_order_order_status_remove_order_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
