# Generated by Django 4.2.1 on 2023-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0004_alter_cart_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
