# Generated by Django 4.2.1 on 2023-06-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0006_order_shop_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="product_name",
        ),
    ]
