# Generated by Django 4.2.1 on 2023-06-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0007_remove_payment_date_remove_payment_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="counciling",
            name="user_id",
        ),
        migrations.AddField(
            model_name="counciling",
            name="description",
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
