# Generated by Django 4.2.1 on 2023-06-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("disabled", "0008_remove_counciling_user_id_counciling_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="workerreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=500)),
                ("place", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("workerstatus", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=10)),
                (
                    "login_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disabled.log"
                    ),
                ),
            ],
        ),
    ]
